name: "Continuous Integration"

on: ["pull_request", "push"]

env:
  fail-fast: true

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        deps:
          - "normal"
        symfony-require:
          - ""
        symfony-deprecations-helper:
          - ""
        include:
          # PHP 8.1 test matrix
          - php-version: "8.1"
            deps: "normal"

          - php-version: "8.1"
            deps: "low"

          - php-version: "8.1"
            deps: "dev"
            
          # Test Symfony 6 with PHP 8.1
          - php-version: "8.1"
            deps: "normal"
            symfony-require: "6.4.*"
            
          # PHP 8.2 test matrix
          - php-version: "8.2"
            deps: "normal"

          - php-version: "8.2"
            deps: "low"

          - php-version: "8.2"
            deps: "dev"
            
          # Test Symfony 7 with PHP 8.2
          - php-version: "8.2"
            deps: "normal"
            symfony-require: "7.0.*"
            
          # PHP 8.3 test matrix
          - php-version: "8.3"
            deps: "normal"

          - php-version: "8.3"
            deps: "low"

          - php-version: "8.3"
            deps: "dev"
            
          # Test latest Symfony with PHP 8.3
          - php-version: "8.3"
            deps: "normal"
            symfony-require: "7.*"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 2

      - name: "Install PHP with PCOV"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "json"
          tools: "composer:2"
          coverage: "pcov"
          ini-values: "memory_limit=-1"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v3"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

      - name: "Require specific Symfony version"
        run: "composer global require --no-progress --no-scripts --no-plugins 'symfony/flex:^2.3'"
        if: "${{ matrix.symfony-require != '' }}"
        
      - name: "Set Symfony version constraint"
        run: "composer config extra.symfony.require ${{ matrix.symfony-require }}"
        if: "${{ matrix.symfony-require != '' }}"

      - name: "Install stable dependencies with composer"
        run: "composer update --no-interaction --prefer-dist --prefer-stable"
        if: "${{ matrix.deps == 'normal' }}"

      - name: "Install dev dependencies with composer"
        run: "composer update --no-interaction --prefer-dist"
        if: "${{ matrix.deps == 'dev' }}"

      - name: "Install lowest possible dependencies with composer"
        run: "composer update --no-interaction --prefer-dist --prefer-stable --prefer-lowest"
        if: "${{ matrix.deps == 'low' }}"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"

      - name: "Upload coverage file"
        uses: "actions/upload-artifact@v4"
        with:
          name: "phpunit-${{ matrix.php-version }}-${{ matrix.deps }}-${{ matrix.symfony-require }}-${{ hashFiles('composer.lock') }}.coverage"
          path: "coverage.xml"

      - uses: codecov/codecov-action@v3
        with:
          verbose: true
